"""init

Revision ID: 00876f524d89
Revises: 
Create Date: 2024-01-27 03:52:02.837210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00876f524d89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toilets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toilets_id'), 'toilets', ['id'], unique=False)
    op.create_table('accessibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('gender_neutral', sa.Boolean(), nullable=True),
    sa.Column('toilet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_id'), 'accessibility', ['id'], unique=False)
    op.create_table('openingHours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.String(length=255), nullable=True),
    sa.Column('close_time', sa.String(length=255), nullable=True),
    sa.Column('toilet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openingHours_id'), 'openingHours', ['id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('toilet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_openingHours_id'), table_name='openingHours')
    op.drop_table('openingHours')
    op.drop_index(op.f('ix_accessibility_id'), table_name='accessibility')
    op.drop_table('accessibility')
    op.drop_index(op.f('ix_toilets_id'), table_name='toilets')
    op.drop_table('toilets')
    # ### end Alembic commands ###
